name: CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Pull Changes
              run: git pull origin master
              working-directory: /home/pranaybatta/simple-shop

            - name: Build and Deploy
              run: |
                  sudo docker compose up --build -d
              working-directory: /home/pranaybatta/simple-shop